FROM golang:1.6-alpine

RUN apk add --no-cache alpine-sdk

RUN git clone https://github.com/docker/swarmkit -b v1.12.0 /go/src/github.com/docker/swarmkit

WORKDIR /go/src/github.com/docker/swarmkit

RUN make binaries