#!/bin/bash -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $dir/common

cd $dir/..

docker build -t $IMAGE-build -f Dockerfile.build .

docker run \
  --rm \
  -v $dir/../code:/usr/src/${APP_PATH} \
  -w /usr/src/${APP_PATH} \
    $IMAGE-build \
      go build

docker build -t $IMAGE .

rm -f code/$NAME