#!/bin/bash -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $dir/common

cd $dir/..

docker build -t $IMAGE-build -f Dockerfile.build .

docker run \
  --rm \
  -v $dir/..:/go/src/${APP_PATH} \
  -w /go/src/${APP_PATH} \
    $IMAGE-build \
      go build

docker build -t $IMAGE .

rm -f $NAME
