#!/bin/bash -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $dir/common

docker run \
  --rm -it \
  -e CATTLE_URL=$CATTLE_URL \
  -e CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY \
  -e CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY \
  -p 32376:32376 \
    $IMAGE $@
