swarmkit-mon:
  image: sourceability/swarmkit:v17.03.1-ce
  environment:
    MANAGER_SCALE: ${MANAGER_SCALE}
  labels:
    io.rancher.container.agent.role: environment
    io.rancher.container.create_agent: 'true'
    io.rancher.container.dns: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
  net: host
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/lib/rancher/state:/var/lib/rancher/state
